package kg.kut.os.mentorhub.notification.entity;

public enum NotificationType {
    PROFILE_VIEWED,
    APPLICATION_APPROVED,
    APPLICATION_REJECTED,
    BOOKING_CREATED,
    BOOKING_CONFIRMED,
    LESSON_CANCELLED,
    LESSON_COMPLETED,
    NEW_REVIEW_RECEIVED,
    UPCOMING_LESSON_REMINDER,
    ACCOUNT_BANNED,
    ACCOUNT_UNBANNED
}
